# file: postgresql/tasks/extensions/extra_packages.yml

- name: PostgreSQL | Extensions | Add repo keys | apt
  apt_key:
    id: "CC9CACA5"
    url: "http://debian.depot.e2.rie.gouv.fr/keys/debian-archive-keyring/236BB7D85E32FCD00ED50F847D82EE6CCC9CACA5.asc"
    state: present
    keyring: /etc/apt/trusted.gpg.d/CC9CACA5.gpg
  when: ansible_os_family == "Debian"

#- name: PostgreSQL | Extensions | Add repos | apt
#  apt_repository:
#    repo: "deb http://debian.depot.e2.rie.gouv.fr/depot-cs/ {{ ansible_distribution_release }} main"
#    state: present
#  when: ansible_os_family == "Debian"

- name: PostgreSQL | Extensions | Add packages | Debug
  debug:
    msg: "{{ postgresql_ext_extra_packages }}"

- name: PostgreSQL | Extensions | Add repos | apt
  apt_repository:
    repo: "{{ item.value }}"
    state: present
  loop: "{{ postgresql_ext_extra_packages.apt_repositories | dict2items }}"

- name: PostgreSQL | Extensions | Add packages | Debian
  apt:
    name: "{{ postgresql_ext_extra_packages.names }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family == "Debian"
